package BrickBreaker;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;


//import com.sun.glass.events.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akash
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    
    public Register() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        rtitle = new javax.swing.JLabel();
        com = new javax.swing.JLabel();
        nick = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        namenick = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        confirmPasswordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        s = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBackground(new java.awt.Color(255, 0, 51));
        name.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 177, 199, 30));

        rtitle.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 36)); // NOI18N
        rtitle.setText("Let'S Play Brick Breaker");
        getContentPane().add(rtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 538, 50));

        com.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        com.setText("Sign Up & Enjoy Your Game!");
        getContentPane().add(com, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 290, -1));

        nick.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        nick.setText("Nick Name");
        getContentPane().add(nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 243, 199, 30));

        pass.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        pass.setText("Set Password");
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 306, 199, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 178, 150, 30));

        namenick.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namenick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namenickActionPerformed(evt);
            }
        });
        getContentPane().add(namenick, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 244, 150, 30));

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 307, 150, 30));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 478, 121, 40));
        getContentPane().add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 368, 150, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel2.setText("Confirm Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 361, -1, 43));

        jButton3.setBackground(new java.awt.Color(102, 255, 102));
        jButton3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton3.setText("SUBMIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 140, 40));

        s.setBackground(new java.awt.Color(255, 255, 255));
        s.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        s.setForeground(new java.awt.Color(255, 255, 255));
        s.setText(" ");
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 370, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tmonut.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1010, 0, 1810, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
        {
            
        }
    }//GEN-LAST:event_formKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Login n=new Login();
n.setVisible(true);
setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void namenickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namenickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namenickActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

         try {
                //Creating Connection Object
                Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/BrickBreaker?useSSL=false","root","root");
                //Preapared Statement
                PreparedStatement Pstatement=connection.prepareStatement("insert into login values(?,?)");
                //Specifying the values of it's parameter
                Pstatement.setString(1,namenick.getText());
               // Pstatement.setString(2,genderComboBox.getSelectedItem().toString());
               // Pstatement.setString(3,fatherTextField.getText());
                Pstatement.setString(2,passwordField.getText());
              //  Pstatement.setString(3,confirmPasswordField.getText());
                //Pstatement.setString(6,cityTextField.getText());
                //Pstatement.setString(7,emailTextField.getText());
                //Checking for the Password match
                if(passwordField.getText().equalsIgnoreCase(confirmPasswordField.getText()))
                {
                    //Executing query
                    Pstatement.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Data Registered Successfully ! Go Back !");
                    s.setText("Registered Successfully");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"password did not match");
                }
 
            } catch (SQLException e1) {
                e1.printStackTrace();
            }
 
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel com;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField namenick;
    private javax.swing.JLabel nick;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel rtitle;
    private javax.swing.JLabel s;
    // End of variables declaration//GEN-END:variables
}
